[2022-11-29T17:58:27.356+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py:871: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti: TaskInstance | None = qry.with_for_update().one_or_none()

[2022-11-29T17:58:27.377+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: etl_dag.modelCreation scheduled__2022-11-29T17:57:25.034163+00:00 [queued]>
[2022-11-29T17:58:27.399+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: etl_dag.modelCreation scheduled__2022-11-29T17:57:25.034163+00:00 [queued]>
[2022-11-29T17:58:27.401+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T17:58:27.403+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-29T17:58:27.405+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T17:58:27.435+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): modelCreation> on 2022-11-29 17:57:25.034163+00:00
[2022-11-29T17:58:27.444+0000] {standard_task_runner.py:54} INFO - Started process 5222 to run task
[2022-11-29T17:58:27.459+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'modelCreation', 'scheduled__2022-11-29T17:57:25.034163+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpueq9k514']
[2022-11-29T17:58:27.462+0000] {standard_task_runner.py:83} INFO - Job 7: Subtask modelCreation
[2022-11-29T17:58:27.467+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/etl_dag.py
[2022-11-29T17:58:29.300+0000] {task_command.py:384} INFO - Running <TaskInstance: etl_dag.modelCreation scheduled__2022-11-29T17:57:25.034163+00:00 [running]> on host 2c28799c9ef4
[2022-11-29T17:58:29.310+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py:873: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti = qry.one_or_none()

[2022-11-29T17:58:29.897+0000] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_dag
AIRFLOW_CTX_TASK_ID=modelCreation
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T17:57:25.034163+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-29T17:57:25.034163+00:00
[2022-11-29T17:58:30.218+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-11-29T17:58:30.263+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py:871: SAWarning: TypeDecorator ExecutorConfigType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  ti: TaskInstance | None = qry.with_for_update().one_or_none()

[2022-11-29T17:58:30.314+0000] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=modelCreation, execution_date=20221129T175725, start_date=20221129T175827, end_date=20221129T175830
[2022-11-29T17:58:30.440+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-11-29T17:58:30.695+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
